In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [29]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [30]:
df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [31]:
#label encoder to convert gender 
gender=LabelEncoder()
df['Gender']=gender.fit_transform(df['Gender'])
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [32]:
from sklearn.preprocessing import OneHotEncoder
geography=OneHotEncoder()
geo_encoder=geography.fit_transform(df[['Geography']])
geo_encoder
geo_code_df=pd.DataFrame(geo_encoder.toarray(),columns=geography.get_feature_names_out(['Geography']))
geo_code_df
data=pd.concat([df.drop('Geography',axis=1),geo_code_df],axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [33]:
with open('gender.pkl','wb') as file:
    pickle.dump(gender,file)
with open('geography.pkl','wb') as file:
    pickle.dump(geography,file)

In [34]:
#train test split
x=data.drop(['EstimatedSalary'],axis=1)
y=data['EstimatedSalary']
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [35]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [36]:
with open('scaler.pkl','wb')as file:
    pickle.dump(scaler,file)

In [37]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
import datetime

In [38]:
# build model
Model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

In [39]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01) # we cn define optimizers like this or also directoly optimizer='Adam'
# we can efine lossed like this or directly like loss='binar_crossentropy'
##complie the model

Model.compile(optimizer=opt,loss='mean_absolute_error',metrics=['accuracy'])

In [40]:
Model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [41]:
#setup the tensorboard 
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir='regressionlogs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [42]:
#set up early stopping 
early_stopping_calling=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [43]:
#train the model
history=Model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_calling]
)

Epoch 1/100
250/250 [==============================] - 5s 11ms/step - loss: 82223.8828 - accuracy: 0.0000e+00 - val_loss: 51564.7344 - val_accuracy: 0.0000e+00
Epoch 2/100
250/250 [==============================] - 2s 8ms/step - loss: 50358.6992 - accuracy: 0.0000e+00 - val_loss: 50586.3125 - val_accuracy: 0.0000e+00
Epoch 3/100
250/250 [==============================] - 2s 6ms/step - loss: 49935.0000 - accuracy: 0.0000e+00 - val_loss: 50331.1055 - val_accuracy: 0.0000e+00
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 49782.6641 - accuracy: 0.0000e+00 - val_loss: 50335.1602 - val_accuracy: 0.0000e+00
Epoch 5/100
250/250 [==============================] - 2s 8ms/step - loss: 49643.6914 - accuracy: 0.0000e+00 - val_loss: 50430.3828 - val_accuracy: 0.0000e+00
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 49618.9805 - accuracy: 0.0000e+00 - val_loss: 50397.7305 - val_accuracy: 0.0000e+00
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 49529.7734 - accuracy: 0.0000e+00 - val_loss: 50195.5195 - val_accuracy: 0.0000e+00
Epoch 8/100
250/250 [==============================] - 2s 6ms/step - loss: 49546.1133 - accuracy: 0.0000e+00 - val_loss: 50356.0391 - val_accuracy: 0.0000e+00
Epoch 9/100
250/250 [==============================] - 2s 7ms/step - loss: 49515.4688 - accuracy: 0.0000e+00 - val_loss: 50315.0508 - val_accuracy: 0.0000e+00
Epoch 10/100
250/250 [==============================] - 2s 9ms/step - loss: 49439.1797 - accuracy: 0.0000e+00 - val_loss: 50311.9414 - val_accuracy: 0.0000e+00
Epoch 11/100
250/250 [==============================] - 2s 7ms/step - loss: 49421.7578 - accuracy: 0.0000e+00 - val_loss: 50406.3359 - val_accuracy: 0.0000e+00
Epoch 12/100
250/250 [==============================] - 2s 8ms/step - loss: 49403.5039 - accuracy: 0.0000e+00 - val_loss: 50295.5703 - val_accuracy: 0.0000e+00
Epoch 13/100
250/250 [==============================] - 2s 8ms/step - loss: 49399.6133 - accuracy: 0.0000e+00 - val_loss: 50389.3047 - val_accuracy: 0.0000e+00
Epoch 14/100
250/250 [==============================] - 2s 7ms/step - loss: 49413.2656 - accuracy: 0.0000e+00 - val_loss: 50294.9375 - val_accuracy: 0.0000e+00
Epoch 15/100
250/250 [==============================] - 2s 7ms/step - loss: 49374.2656 - accuracy: 0.0000e+00 - val_loss: 50323.8555 - val_accuracy: 0.0000e+00
Epoch 16/100
250/250 [==============================] - 2s 7ms/step - loss: 49360.4219 - accuracy: 0.0000e+00 - val_loss: 50438.5391 - val_accuracy: 0.0000e+00
Epoch 17/100
250/250 [==============================] - 1s 6ms/step - loss: 49315.4297 - accuracy: 0.0000e+00 - val_loss: 50331.7227 - val_accuracy: 0.0000e+00

In [44]:
Model.save('regression_model.h5')

d:\deep learning\ann\venv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

HyperParamtereTunning

In [78]:
from sklearn.pipeline import Pipeline
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [88]:
x=data.drop(['Exited'],axis=1)
y=data['Exited']
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [80]:
y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [81]:
#define a function to create model and try diff parameters(keras classifier)

def create_model(neurons=32,layers=1):
    Model=Sequential()
    Model.add(Dense(neurons,activation='relu',input_shape=(x_train.shape[1],)))

    for _ in range(layers-1):
        Model.add(Dense(neurons,activation='relu'))

    Model.add(Dense(1))
    Model.compile(optimizer='adam',loss='binary_classentropy',metrics=['accuracy'])
    return Model

In [82]:
#create a keras classiffier 
Model=KerasClassifier(layer=1,neurons=32,build_fn=create_model,verbose=1)

In [83]:
#define grid search parameters
param_grid={
    'neurons':[16,32,64,128],
    'layers':[1,2],
    'epochs':[50,100]
}

In [86]:
#perform grid search 

# grid=GridSearchCV(estimator=Model,param_grid=param_grid,n_jobs=-1,cv=3,verbose=1)
# grid_result=grid.fit(x_train, y_train)
grid = GridSearchCV(estimator=Model, param_grid=param_grid, n_jobs=-1, cv=3, verbose=1)
grid_result = grid.fit(x_train, y_train)
print("Best Accuracy: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
#print the parameters
# print("best: %f using %s" % (grid_result.best_score_,grid_result.best_params_))

AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [89]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, RMSprop
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV

# Define a function that builds your model
def create_model(optimizer='adam'):
    model = Sequential()
    model.add(Dense(12, input_dim=x_train.shape[1], activation='relu'))  # update input_dim if needed
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# ✅ Wrap the model
model = KerasClassifier(model=create_model, verbose=0)

# ✅ Define the parameter grid
param_grid = {
    'model__optimizer': ['adam', 'rmsprop'],
    'batch_size': [10, 20],
    'epochs': [10, 50]
}

# ✅ Use GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3, verbose=1)
grid_result = grid.fit(x_train, y_train)

# ✅ Show results
print("Best Accuracy: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

AttributeError: 'super' object has no attribute '__sklearn_tags__'